backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Subtitle", name: "subtitle", widget: "string"}
        - label: 'Projects'
          name: "projects"
          widget: list
          fields:
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
        - { label: "Footer", name: 'footer', widget: 'string' }